CREATE TABLE IF NOT EXISTS `form_data` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) DEFAULT NULL,
  `EMAIL` varchar(25) DEFAULT NULL,
  `MESSAGE` varchar(255) DEFAULT NULL,
  `CONTACT_REASON` varchar(20) DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `TIME` time DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
COMMIT;
